version: '2'

services:
  web:
    build: .
    depends_on:
      - db
      - cache
    env_file:
      - .env.dist
      - .env
    image: dkrud5g/magentostack
    ports:
      - "80:80"
      - "443:443"
    links:
      - db:mysqlhost
      - cache:redishost
    volumes:
      - ./var/www:/var/www
      - ./conf/sites-enabled:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
      - ./logs/supervisor:/var/log/supervisor
  db:
    image: mysql:latest
    env_file:
      - .env.dist
      - .env
  cache:
    image: redis:latest
