version: '2'

services:
  magento:
    build: .
    depends_on:
      - db
      - cache
      - phpmyadmin
    env_file:
      - .env.dist
      - .env
    image: dkrud5g/magentostack
    links:
      - db:mysqlhost
      - cache:redishost
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./var/www:/var/www
      - ./conf/sites-available:/etc/apache2/sites-available
      - ./conf/sites-enabled:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
      - ./logs/supervisor:/var/log/supervisor
      - ./var/events:/var/events
  db:
    image: mysql:latest
    env_file:
      - .env.dist
      - .env
    volumes:
      - ./var/mysql/datadir:/var/lib/mysql
  cache:
    image: redis:latest
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    links:
      - db:mysqlhost
    environment:
      - PMA_HOST=mysqlhost
      - PMA_VERBOSE=mysqlhost
      - PMA_USER=root
      - PMA_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./var/phpmyadmin/config.user.inc.php:/www/config.user.inc.php
      - ./var/phpmyadmin/sql:/www/sql

